export enum City {
  ARIANA = 'Ariana',
  BEJA = 'Beja',
  BEN_AROUS = 'Ben Arous',
  BIZERTE = 'Bizerte',
  GAFSA = 'Gafsa',
  GABES = 'Gabès',
  HAMMAMET = 'Hammamet',
  JENDOUBA = 'Jendouba',
  KAIROUAN = 'Kairouan',
  KASSERINE = 'Kasserine',
  KEBILI = 'Kebili',
  KEF = 'Kef',
  MAHDIA = 'Mahdia',
  MANOUBA = 'Manouba',
  MEDENINE = 'Medenine',
  MONASTIR = 'Monastir',
  NABEUL = 'Nabeul',
  SFAX = 'Sfax',
  SIDI_BOUZID = 'Sidi Bouzid',
  SILIANA = 'Siliana',
  SOUSSE = 'Sousse',
  TATAOUINE = 'Tataouine',
  TOZEUR = 'Tozeur',
  TUNIS = 'Tunis',
  ZAGHOUAN = 'Zaghouan',


}